SECRET_KEY_BASE: something-at-least-thirty-characters-long
TWITTER_CONSUMER_KEY: key-goes-here
TWITTER_CONSUMER_SECRET: secret-goes-here
LOCALE: en
AWS_ACCESS_KEY_ID: xxxx
AWS_SECRET_ACCESS_KEY: xxxx
FOG_DIRECTORY: "***BUCKET_NAME****"
FOG_PROVIDER: "AWS"
FOG_REGION: "eu-west-1"
ASSET_SYNC_GZIP_COMPRESSION: "true"
ASSET_SYNC_MANIFEST: "true"
ASSET_SYNC_EXISTING_REMOTE_FILES: "delete"